# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/9bbabc1f92e14ff33431e7d8b0d525f0a29f4103/hyperparams/sac.yml#L2
name: SACAgent
config:
  gamma: 0.9999
  polyak: 0.99 # (1 - tau)
  lr: 0.0003
  alpha: 0.2 # ent_coef
  steps_to_sample_randomly: 10 # start_steps
  actor_critic_cfg: './config_files/mcar_sac/network.yaml'