apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: l2r-sequential
  labels:
    tier: worker-set
spec:
  # 2 to start, then for phortx 30-40 is the upper bound probably
  replicas: 1
  selector:
    matchLabels:
      tier: worker-set
  template:
    metadata:
      labels:
        tier: worker-set
    spec:
      # nodeSelector:
      #   # we don't specify the cluster, maybe it's ok to just delete the phortx stuff?
      #   # 1-3
      #   nodetype: 1
      containers:
      - name: worker-container
        tty: true
        stdin: true
        resources: # Maybe a good idea to have the learner on its own gpu, specify like below
            limits:
                nvidia.com/gpu: 1
        env:
        # This is the tricky bit, We're not claiming the pods, we might end up sharing it
        # not-yet done bit: multiple worker sets for each gpu group in the hardware
        #### Change GPUs if you want more replica sets
        # "{{GPU_ID}}" 
          - name: NVIDIA_VISIBLE_DEVICES 
            value: "2" # 0-7??
          - name: CUDA_VISIBLE_DEVICES
            value: "0" # has to match the above
        image: docker.pdl.cmu.edu/l2r2022:latest
        command:
          - /bin/bash
          - -c
          - apt-get update && git clone https://github.com/BrandonBian/l2r && cd l2r && git checkout sequential-l2r && pip install git+https://github.com/learn-to-race/l2r@aicrowd-environment && pip install -r setup/devtools_reqs.txt && pip install "opencv-python-headless<4.3" && sleep infinity

--- 
apiVersion: v1
kind: Service
metadata:
  name: l2r-sequential-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: learner-service-port
    protocol: TCP
    port: 4444
    targetPort: learner-port
