apiVersion: v1
kind: Pod
metadata:
  name: mcar-sequential
  labels:
    tier: worker-set
spec:
  containers:
  - name: worker-container
    tty: true
    stdin: true
    resources:
      limits:
        nvidia.com/gpu: 1
    env:
    - name: NVIDIA_VISIBLE_DEVICES
      value: "2" # 0-7??
    - name: CUDA_VISIBLE_DEVICES
      value: "0" # has to match the above
    image: docker.pdl.cmu.edu/jingyua4/safepo:v1
    command:
    - /bin/bash
    - -c
    - cd / &&
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys A4B469963BF863CC &&
      sudo apt-get update &&
      sudo apt-get install -y python3.8 python3.8-dev python3.8-distutils python3.8-venv swig &&
      wget https://bootstrap.pypa.io/get-pip.py &&
      sudo python3.8 get-pip.py &&
      apt install -y git &&
      git clone https://github.com/BrandonBian/l2r-distributed.git &&
      cd l2r-distributed &&
      git checkout sequential &&
      pip install --upgrade pip setuptools wheel &&
      pip install git+https://github.com/learn-to-race/l2r@aicrowd-environment &&
      pip install -r setup/devtools_reqs.txt &&
      pip install "opencv-python-headless<4.3" gym[box2d] protobuf==3.20.* &&
      python3.8 -m scripts.main --env mcar --wandb_apikey 173e38ab5f2f2d96c260f57c989b4d068b64fb8a
