apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: TODO
  labels:
    tier: TODO
spec:
  # 2 to start, then for phortx 30-40 is the upper bound probably
  replicas: TODO
  selector:
    matchLabels:
      tier: TODO
  template:
    metadata:
      labels:
        tier: TODO
    spec:
      nodeSelector:
        # we don't specify the cluster, maybe it's ok to just delete the phortx stuff?
        # 1-3
        nodetype: phortx

      containers:
        - name: TODO
          tty: true
          stdin: true
          resources: # Maybe a good idea to have the learner on its own gpu, specify like below
            limits:
              nvidia.com/gpu: 1
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "0"
            - name: CUDA_VISIBLE_DEVICES
              value: "0"
          image: docker.pdl.cmu.edu/jingyua4/safepo:v1
          command: # remember to configure 'AGENT_NAME' and 'TRAINING_PARADIGM'
            - /bin/bash
            - -c
            - cd / &&
              sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys A4B469963BF863CC &&
              sudo apt-get update &&
              sudo apt-get install -y python3.8 python3.8-dev python3.8-distutils python3.8-venv swig &&
              wget https://bootstrap.pypa.io/get-pip.py &&
              sudo python3.8 get-pip.py &&
              apt install -y git &&
              git clone https://github.com/BrandonBian/l2r-distributed.git &&
              cd l2r-distributed &&
              pip install --upgrade pip setuptools wheel &&
              pip install git+https://github.com/learn-to-race/l2r@aicrowd-environment &&
              pip install -r setup/devtools_reqs.txt &&
              pip install "opencv-python-headless<4.3" gym[box2d] protobuf==3.20.* && 
              pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113 && 
---
apiVersion: v1
kind: Pod
metadata:
  name: TODO
  labels:
    app.kubernetes.io/name: proxy
spec:
  hostname: learner-1
  nodeSelector:
    nodetype: phortx
  containers:
    - name: TODO
      tty: true
      stdin: true
      resources: # Maybe a good idea to have the learner on its own gpu, specify like below
        limits:
          nvidia.com/gpu: 1
      image: docker.pdl.cmu.edu/jingyua4/safepo:v1 # Slightly different image or files or git repo
      command: # remember to configure 'AGENT_NAME' and 'TRAINING_PARADIGM'
        - /bin/bash
        - -c
        - cd / &&
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys A4B469963BF863CC &&
          sudo apt-get update &&
          sudo apt-get install -y python3.8 python3.8-dev python3.8-distutils python3.8-venv swig &&
          wget https://bootstrap.pypa.io/get-pip.py &&
          sudo python3.8 get-pip.py &&
          apt install -y git &&
          git clone https://github.com/BrandonBian/l2r-distributed.git &&
          cd l2r-distributed &&
          pip install --upgrade pip setuptools wheel &&
          pip install git+https://github.com/learn-to-race/l2r@aicrowd-environment &&
          pip install -r setup/devtools_reqs.txt &&
          pip install "opencv-python-headless<4.3" gym[box2d] protobuf==3.20.* && 
          pip install tianshou && 
          pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113 &&
      ports:
        - name: TODO
          containerPort: 4444
---
apiVersion: v1
kind: Service
metadata:
  name: TODO
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
    - name: TODO
      protocol: TCP
      port: 4444
      targetPort: TODO
