name: OpenAIRunner
config:
  agent_config_path: "config_files/walker-openai/agent.yaml"
  buffer_config_path: "config_files/walker-openai/buffer.yaml"
  env_config_path: "config_files/walker-openai/env.yaml"
  steps_per_epoch: 4000
  epochs: 500000
  start_steps: 10000
  max_ep_len: 1600
  update_after: 1000
  update_every: 50
  batch_size: 512
  num_test_episodes: 10
